config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'messages#index'

  resources :messages, only: [:index]

  mount Api::Base => '/'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  SENT      = 'sent'
  DELIVERED = 'delivered'
  FAILED    = 'failed'
  INVALID   = 'invalid'
  STATUSES = [SENT, DELIVERED, FAILED, INVALID].freeze

  validates :phone_number, presence:  true
  validates :text,         presence:  true
  validates :status,       presence:  true
  validates :status,       inclusion: { in: STATUSES }
end

app/controllers/api/base.rb
# frozen_string_literal: true

module Api
  class Base < Grape::API
    version 'v1', using: :path
    format :json
    prefix 'api'

    rescue_from Grape::Exceptions::ValidationErrors do |e|
      error!({ errors: e.full_messages }, 400)
    end

    rescue_from Errors::UnprocessableError do |e|
      error!({ errors: [e.message] }, 400)
    end

    rescue_from :all do |e|
      error!({ errors: [e.message] }, 500)
    end

    mount Api::DeliveryStatuses
    mount Api::Messages
    mount Api::Missing     # should be mount as very last one !!!
  end
end

app/controllers/api/delivery_statuses.rb
# frozen_string_literal: true

module Api
  class DeliveryStatuses < Grape::API
    resource :delivery_statuses do
      desc 'Update message status.' do
        params status:     { in: 'body' }
        params message_id: { in: 'body' }
      end

      params do
        requires :status,     type: String, allow_blank: false, values: Message::STATUSES
        requires :message_id, type: String, allow_blank: false
      end

      post do
        UpdateMessageService.update_message_status(params: params)

        { success: true }
      end
    end
  end
end

app/controllers/api/messages.rb
# frozen_string_literal: true

module Api
  class Messages < Grape::API
    resource :messages do
      desc 'Send text message.' do
        params phone_number: { in: 'body' }
        params text: { in: 'body' }
      end

      params do
        requires :phone_number, type: String
        requires :text,         type: String
      end

      post do
        CreateMessageService.create_and_send_message(params: params)

        { success: true }
      end
    end
  end
end

app/controllers/api/missing.rb
# frozen_string_literal: true

module Api
  class Missing < Grape::API
    desc 'All other routes should return not-found', hidden: true
    route :any, '*path' do
      not_found_error!
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  def index
    @messages = ::MessagesQuery.find_messages(params: params)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TextingService</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<div class="ui right aligned basic segment">
  <div class="ui action input">
    <%= form_with url: messages_path, method: :get do |form| %>
      <div class="ui input">
        <%= form.text_field :phone_number, value: params[:phone_number] %>
      </div>

      <%= form.submit 'Search', class: 'ui button' %>
    <% end %>

    <%= link_to 'Clear Search', messages_path, class: 'ui secondary button' %>
  </div>
</div>

<table class="ui celled table">
  <thead>
    <tr>
      <th>Message ID</th>
      <th>Text</th>
      <th>Phone Number</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% @messages.each do |message| %>
      <tr id="messages-<%=message.id%>">
        <td class="t-id"><%= message.id %></td>
        <td class="t-text"><%= message.text %></td>
        <td class="t-phone_number"><%= message.phone_number %></td>
        <td class="t-status"><%= message.status.humanize %></td>
      </tr>
    <% end %>
  </tbody>
</table>